Repository just-the-docs/just-the-docs, pull requests merged in 2020-06, with the labels that each got.

#352 Navigation improvements and search sections
  404.html
  _config.yml
  _includes/nav.html
  _layouts/default.html
  _sass/code.scss
  _sass/color_schemes/dark.scss
  _sass/content.scss
  _sass/layout.scss
  _sass/navigation.scss
  _sass/search.scss
  _sass/support/_variables.scss
  assets/js/just-the-docs.js
  assets/js/search-data.json
  assets/js/zzzz-search-data.json
  docs/configuration.md
  docs/search.md
  lib/tasks/search.rake
Labels: enhancement, next-minor-release

#348 Remove constraint with jekyll 4.1.0
  just-the-docs.gemspec
Labels: bug

#362 Add print styles
  _layouts/default.html
  _sass/modules.scss
  _sass/print.scss
Labels: enhancement

#367 Pdmosses collapsible toc
  _sass/content.scss
  docs/navigation-structure.md
Labels: next-minor-release

#368 Remove collapsible TOC on nav doc
  docs/navigation-structure.md
Labels: patch
