Repository just-the-docs/just-the-docs, pull requests merged in 2022-03, with the labels that each got.

#364 allow custom favicon code
  _includes/favicon.html
  _includes/head.html
  index.md
Labels: needs-documentation, feature

#221 Fix image link not working
  docs/index-test.md
Labels: bug

#782 Fix images in Markdown kitchen sink
  assets/images/large-image.jpg
  assets/images/small-image.jpg
  docs/index-test.md
Labels: question, patch

#790 updates Code of Conduct to Contributor Covenant v2.1
  CODE_OF_CONDUCT.md
Labels: chore
